---

- name: Apply web-terminal subscription
  k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: web-terminal
        namespace: openshift-operators
      spec:
        channel: alpha
        name: web-terminal
        source: redhat-operators
        sourceNamespace: openshift-marketplace
